CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(255) PRIMARY KEY,
  email VARCHAR(255) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  role VARCHAR(50) DEFAULT 'user',
  password_hash VARCHAR(255) DEFAULT NULL,
  created_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL,
  last_login DATETIME DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) DEFAULT NULL,
  token VARCHAR(255) DEFAULT NULL,
  ip_address VARCHAR(100) DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  expires_at DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS devices (
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) DEFAULT NULL,
  device_name VARCHAR(255) DEFAULT NULL,
  phone_model VARCHAR(255) DEFAULT NULL,
  battery INT DEFAULT 0,
  charging TINYINT(1) DEFAULT 0,
  carrier VARCHAR(255) DEFAULT NULL,
  sim_number VARCHAR(100) DEFAULT NULL,
  status VARCHAR(50) DEFAULT 'offline',
  last_seen DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT NULL,
  socket_id VARCHAR(255) DEFAULT NULL,
  network_type VARCHAR(50) DEFAULT NULL,
  ram_usage VARCHAR(50) DEFAULT NULL,
  storage_usage VARCHAR(50) DEFAULT NULL,
  cpu_usage VARCHAR(50) DEFAULT NULL,
  ip_address VARCHAR(100) DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS api_keys (
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) DEFAULT NULL,
  `key` VARCHAR(255) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  allowed_ips TEXT DEFAULT NULL,
  status VARCHAR(50) DEFAULT 'active',
  usage_count INT DEFAULT 0,
  last_used DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS webhooks (
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) DEFAULT NULL,
  url TEXT DEFAULT NULL,
  events JSON DEFAULT NULL,
  secret VARCHAR(255) DEFAULT NULL,
  status VARCHAR(50) DEFAULT 'active',
  created_at DATETIME DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS webhook_deliveries (
  id VARCHAR(255) PRIMARY KEY,
  webhook_id VARCHAR(255) DEFAULT NULL,
  user_id VARCHAR(255) DEFAULT NULL,
  event VARCHAR(100) DEFAULT NULL,
  status VARCHAR(50) DEFAULT NULL,
  response_code INT DEFAULT NULL,
  created_at DATETIME DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS sms_queue (
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) DEFAULT NULL,
  device_id VARCHAR(255) DEFAULT NULL,
  phone_number VARCHAR(50) DEFAULT NULL,
  message TEXT DEFAULT NULL,
  sim_slot INT DEFAULT 1,
  priority INT DEFAULT 0,
  webhook_url TEXT DEFAULT NULL,
  metadata JSON DEFAULT NULL,
  status VARCHAR(50) DEFAULT 'pending',
  retry_count INT DEFAULT 0,
  max_retries INT DEFAULT 3,
  error TEXT DEFAULT NULL,
  source_ip VARCHAR(100) DEFAULT NULL,
  country VARCHAR(100) DEFAULT NULL,
  api_key_id VARCHAR(255) DEFAULT NULL,
  request_id VARCHAR(255) DEFAULT NULL,
  sent_at DATETIME DEFAULT NULL,
  delivered_at DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS sms_history (
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) DEFAULT NULL,
  device_id VARCHAR(255) DEFAULT NULL,
  phone_number VARCHAR(50) DEFAULT NULL,
  message TEXT DEFAULT NULL,
  sim_slot INT DEFAULT 1,
  status VARCHAR(50) DEFAULT 'pending',
  error TEXT DEFAULT NULL,
  duration INT DEFAULT NULL,
  request_id VARCHAR(255) DEFAULT NULL,
  api_key_id VARCHAR(255) DEFAULT NULL,
  sent_at DATETIME DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS logs (
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) DEFAULT NULL,
  action VARCHAR(100) DEFAULT NULL,
  details JSON DEFAULT NULL,
  ip_address VARCHAR(100) DEFAULT NULL,
  status VARCHAR(50) DEFAULT NULL,
  created_at DATETIME DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS settings (
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) DEFAULT NULL,
  timezone VARCHAR(100) DEFAULT 'UTC',
  language VARCHAR(10) DEFAULT 'en',
  theme VARCHAR(20) DEFAULT 'system',
  notifications_enabled TINYINT(1) DEFAULT 1,
  created_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS gateway_state (
  user_id VARCHAR(255) PRIMARY KEY,
  paused TINYINT(1) DEFAULT 0,
  updated_at DATETIME DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) DEFAULT NULL,
  token VARCHAR(255) DEFAULT NULL,
  expires_at DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT NULL
);
